### ISSUE TITLE
Overwritable default buttons

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#28]
The old SimpleMDE field had this too and I found it pretty useful. In the `site/config.php` you could define:

```php
'community.markdown-field.buttons' => ['headlines', 'bold', 'italic']
```

I already started with it, but I think we need to change the `array_merge_recursive()` function in `lib/fields/markdown.php` as it doesn't allow overwriting existing props. If I understand it correctly it only adds another `buttons` to the `props` array. See https://medium.com/@kcmueller/php-merging-two-multi-dimensional-arrays-overwriting-existing-values-8648d2a7ea4f

After that we should be able to just add something like this to the `lib/fields/markdown.php` file:
```php
'buttons' => function() {
  return option('community.markdown-field.buttons');
}
```
...and this to the `/config.php` file:
```php
'options' => array(
  'buttons' => ['headlines', 'bold', 'italic', 'divider', 'link', 'email', 'code', 'divider', 'ul', 'ol']
)
```

**Comment by sylvainjule** [comment]
Overwriting existing values should be done in a `array_replace_recursive` callback. 

The toolkit actually has a `A::merge` function that allows merging arrays in a cleaner way. I'm planning to replace it.

In the end, prop should probably look like this though, to allow overwriting the config on a per-field basis:

```php
'buttons' => function($buttons = null) {
  return $buttons ?? option('community.markdown-field.buttons');
}
```
Then we'll be able to get rid of https://github.com/sylvainjule/kirby-markdown-field/blob/6d365b233938cbf67eac76ce2d5886d948b672a9/src/components/toolbar/MarkdownToolbar.vue#L23-L25

This global settings, rather than on a per-field basis, could also benefit the other options.

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/1a62cc309dd1a009e257790749e45ac9c67c6c50 ✅
