### ISSUE TITLE
Hide markdown.

### ISSUE THREAD

**Issue by louiswalch** [sylvainjule/kirby-markdown-field#58]
Can the markdown characters be hidden to make this a bit more non-developer friendly? My clients would certainly be confused why "##" appears before the text once they choose to make it a heading.

**Comment by sylvainjule** [comment]
Unfortunately it cannot, not easily at least (well, technically you can hide them with one CSS rule, but as you can imagine it leads to a bunch of issues). 

One solution would be to combine it with Prosemirror somehow, but I think this wouldn't be worth the effort since there is a promising and good-looking Vue WYSIWYG editor ([tiptap](https://tiptap.scrumpy.io/)). It's just missing a markdown import/export feature to be a perfect wysiwyg-plugin candidate.

You're not the only one to miss it, there's an ongoing discussion about editor plugins: https://github.com/getkirby/plugins/issues/1

**Comment by sylvainjule** [comment]
Tiptap's developer just mentioned that he's currently working on this, so closing the ticket as in the near future it will be the best option. 👍
