### ISSUE TITLE
Strange problem with Markdown-field and Kirby-builder

### ISSUE THREAD

**Issue by janstieler** [sylvainjule/kirby-markdown-field#70]
Hi,
after I installed Kirby 3.0.2 and the [Kirbybuilder](https://github.com/TimOetting/kirby-builder) I have the problem that I get an error in the panel `Cannot read property 'name' of null` where I have used the markdown-field.
After some testing I identified the headlinebuttons as the problem. If I delete all 
headlinebuttons the problem was gone. But if I write `- headline` without the array of `- h1 …` etc. it works also.
As last I deleted the indent after `- headlines` for the `- h1 …` it worked again well.
I don't know where the problem is but this hint should be write down in the documentation.

Cheers

**Comment by sylvainjule** [comment]
I am closing the issue since it isn't related to the markdown field itself. 

The headlines subarray not working is probably due to how the builder plugin [is cloning](https://github.com/TimOetting/kirby-builder/blob/34cfe18313fe528fc2d1db214a70ea02e669e912/config.php#L58) the field's options, somehow it the subarray causes issue and ends up being passed as `null`. Props show:

```json
buttons: Array[1]
  0: null
```

You should probably overwrite the buttons in your config.php for now, and see with Tim if he finds a workaround for this.
