### ISSUE TITLE
Missing spellcheck option

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#71]
Seems like the spellcheck option is missing from this field.

The regular textarea field has this option, just like a regular text field.

It seems like the [option is missing in the textarea docs](https://forum.getkirby.com/t/no-spellcheck-for-textareas/13648), but it's definitely possible to set `spellcheck` to `true`.

EDIT:

The field gets the `spellcheck` attribute, but it doesn't do anything. Maybe the [disableSpellcheck](https://codemirror.net/1/manual.html) option has to be set to `false` in this case?

**Comment by sylvainjule** [comment]
I've looked into this. Since the Codemirror editor isn't a regular textarea, the browser's default `spellcheck` cannot apply.

The `disableSpellcheck` you're mentioning links to an outdated documentation, this option doesn't exist anymore.

There is a spell-check plugin (https://github.com/sparksuite/codemirror-spell-checker), but it seems that it's not maintained anymore, plus Javascript spell-checking with Typo.js requires freaking huge dictionaries, around 700ko-1.2mb.

Unfortunately I think there's not satisfying way to add spellcheck to the field, I've marked this as `wontfix` and will close the issue.

If anyone has an idea, feel free to open a new ticket or ask to reopen this one. :)
